"""Domain exceptions for User Management context."""

from .core import (
    UserManagementException,
    UserNotFoundError,
    EmailAlreadyExistsError,
    UserInactiveError,
    StudentNotFoundError,
    StudentIdAlreadyExistsError,
    InvalidStudentIdFormatError,
    StudentCannotHavePasswordError,
    StudentCannotLoginError,
    LecturerNotFoundError,
    ProgramNotFoundError,
    StreamRequiredError,
    StreamNotAllowedError,
    StreamNotInProgramError,
    InvalidYearError,
    InvalidDepartmentNameError,
    InvalidCredentialsError,
    InvalidPasswordError,
    WeakPasswordError,
    InvalidTokenError,
    ExpiredTokenError,
    InvalidTokenTypeError,
    TokenAlreadyUsedError,
    UnauthorizedError,
)

__all__ = [
    "UserManagementException",
    "UserNotFoundError",
    "EmailAlreadyExistsError",
    "UserInactiveError",
    "StudentNotFoundError",
    "StudentIdAlreadyExistsError",
    "InvalidStudentIdFormatError",
    "StudentCannotHavePasswordError",
    "StudentCannotLoginError",
    "LecturerNotFoundError",
    "ProgramNotFoundError",
    "StreamRequiredError",
    "StreamNotAllowedError",
    "StreamNotInProgramError",
    "InvalidYearError",
    "InvalidDepartmentNameError",
    "InvalidCredentialsError",
    "InvalidPasswordError",
    "WeakPasswordError",
    "InvalidTokenError",
    "ExpiredTokenError",
    "InvalidTokenTypeError",
    "TokenAlreadyUsedError",
    "UnauthorizedError",
]
