# Generated by Django 4.2.25 on 2025-10-26 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(db_index=True)),
                ('generated_by', models.IntegerField()),
                ('generated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'reporting_report',
            },
        ),
    ]
