# Generated by Django 5.2.7 on 2025-12-16 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("session_management", "0002_add_time_range_exclusion"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                ("email_id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.TextField(help_text="JWT token for attendance link")),
                (
                    "token_expires_at",
                    models.DateTimeField(help_text="When the JWT token expires"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Email delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When notification was created"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When email was successfully sent (NULL if not sent)",
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session this notification is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="session_management.session",
                    ),
                ),
                (
                    "student_profile",
                    models.ForeignKey(
                        help_text="Student recipient of this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_notifications",
                        to="user_management.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Notification",
                "verbose_name_plural": "Email Notifications",
                "db_table": "email_notifications",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["session"], name="idx_email_session_id"),
                    models.Index(
                        fields=["student_profile"], name="idx_email_student_id"
                    ),
                    models.Index(fields=["status"], name="idx_email_status"),
                    models.Index(fields=["token"], name="idx_email_token"),
                    models.Index(fields=["created_at"], name="idx_email_created_at"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "student_profile"),
                        name="unique_email_per_student_session",
                        violation_error_message="Email already exists for this student in this session",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("token_expires_at__gt", models.F("created_at"))
                        ),
                        name="token_expiry_future",
                        violation_error_message="Token expiry must be after creation time",
                    ),
                ],
            },
        ),
    ]
