# Generated by Django 5.2.7 on 2025-12-22 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("session_management", "0002_add_time_range_exclusion"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("attendance_id", models.AutoField(primary_key=True, serialize=False)),
                ("time_recorded", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "present"), ("late", "late")],
                        max_length=20,
                    ),
                ),
                ("is_within_radius", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="session_management.session",
                    ),
                ),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="user_management.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
                "indexes": [
                    models.Index(fields=["student_profile"], name="idx_att_student"),
                    models.Index(fields=["session"], name="idx_att_session"),
                    models.Index(fields=["status"], name="idx_att_status"),
                    models.Index(
                        fields=["time_recorded"], name="idx_att_time_recorded"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student_profile", "session"),
                        name="uq_attendance_student_session",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__gte", -90), ("latitude__lte", 90)
                        ),
                        name="ck_att_lat_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__gte", -180), ("longitude__lte", 180)
                        ),
                        name="ck_att_lon_range",
                    ),
                ],
            },
        ),
    ]
