# Generated by Django 5.2.7 on 2025-11-04 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "academic_structure",
            "0002_course_alter_program_options_alter_stream_options_and_more",
        ),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("time_created", models.DateTimeField()),
                ("time_ended", models.DateTimeField()),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                (
                    "location_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="academic_structure.course",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="user_management.lecturerprofile",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="academic_structure.program",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="academic_structure.stream",
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
                "indexes": [
                    models.Index(fields=["course"], name="idx_sessions_course_id"),
                    models.Index(fields=["lecturer"], name="idx_sessions_lecturer_id"),
                    models.Index(
                        fields=["program", "stream"], name="idx_sessions_program_stream"
                    ),
                    models.Index(
                        fields=["time_created", "time_ended"], name="idx_sessions_time"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("time_ended__gt", models.F("time_created"))
                        ),
                        name="ck_time_window_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__gte", -90), ("latitude__lte", 90)
                        ),
                        name="ck_lat_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__gte", -180), ("longitude__lte", 180)
                        ),
                        name="ck_lon_range",
                    ),
                ],
            },
        ),
    ]
