# Generated by Django 5.2.7 on 2025-11-04 07:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0001_initial"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "course_code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Course code must match pattern e.g. CS201",
                                regex="^[A-Z]{2,4}[0-9]{3}$",
                            )
                        ],
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "courses",
                "ordering": ["course_code"],
            },
        ),
        migrations.AlterModelOptions(
            name="program",
            options={"ordering": ["program_name"]},
        ),
        migrations.AlterModelOptions(
            name="stream",
            options={"ordering": ["program_id", "year_of_study", "stream_name"]},
        ),
        migrations.AlterUniqueTogether(
            name="stream",
            unique_together=set(),  # Remove old unique_together first
        ),
        migrations.RemoveField(
            model_name="program",
            name="name",
        ),
        migrations.AddField(
            model_name="program",
            name="department_name",
            field=models.CharField(
                default="general",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="program",
            name="program_code",
            field=models.CharField(
                default="TMP",
                max_length=3,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Program code must be 3 uppercase letters",
                        regex="^[A-Z]{3}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="program",
            name="program_name",
            field=models.CharField(
                default="TMP001",
                max_length=200,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stream",
            name="stream_name",
            field=models.CharField(
                default="unknown",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stream",
            name="year_of_study",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(
                fields=["program_code"], name="idx_programs_program_code"
            ),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(
                fields=["department_name"], name="idx_programs_department"
            ),
        ),
        migrations.AddIndex(
            model_name="stream",
            index=models.Index(fields=["program"], name="idx_streams_program_id"),
        ),
        migrations.AddIndex(
            model_name="stream",
            index=models.Index(fields=["year_of_study"], name="idx_streams_year"),
        ),
        migrations.AddField(
            model_name="course",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="user_management.lecturerprofile",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academic_structure.program",
            ),
        ),
        migrations.RemoveField(
            model_name="stream",
            name="name",
        ),
        migrations.AlterUniqueTogether(
            name="stream",
            unique_together={("program", "stream_name", "year_of_study")},
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["program"], name="idx_courses_program"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["lecturer"], name="idx_courses_lecturer"),
        ),
    ]
