# Generated by Django 5.2.7 on 2025-11-05 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_structure",
            "0002_course_alter_program_options_alter_stream_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(
                max_length=6,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Course code must be exactly 6 uppercase alphanumeric characters (e.g., BCS012, BEG230, DIT410)",
                        regex="^[A-Z0-9]{6}$",
                    )
                ],
            ),
        ),
    ]
