# Generated by Django 5.2.7 on 2025-11-05 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0003_update_course_code_validation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="department_name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.MaxLengthValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="department_name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.MaxLengthValidator(50),
                ],
            ),
        ),
    ]
