# Generated by Django 5.2.7 on 2026-02-25 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0004_update_department_name_validation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="stream",
            name="stream_name",
            field=models.CharField(
                max_length=50, validators=[django.core.validators.MinLengthValidator(2)]
            ),
        ),
    ]
